version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
      - DB_CONNECTION=sqlsrv
      - DB_HOST=db
      - DB_PORT=1433
      - DB_DATABASE=laravel
      - DB_USERNAME=sa
      - DB_PASSWORD=YourStrongPassword123
    command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

  fixer:
    image: php:8.2-cli
    container_name: php-fixer
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["vendor/bin/php-cs-fixer"]
